### ISSUE TITLE
AZURE_TOKEN_CREDENTIALS environment variable not respected - ManagedIdentityCredential never attempted

### ISSUE THREAD

**Issue by tingwei3931** [microsoft/mcp#1030]
## Summary

The `AZURE_TOKEN_CREDENTIALS` environment variable (introduced in PR #56) is not being respected at runtime. Despite setting `AZURE_TOKEN_CREDENTIALS="prod"` or `AZURE_TOKEN_CREDENTIALS="ManagedIdentityCredential"`, the credential chain always falls through to `InteractiveBrowserCredential`, which fails in server environments (Azure Web App, Function Apps, Container Apps).

This prevents the use of Managed Identity authentication in production Azure hosting environments, which is a critical blocker for enterprise deployments.

## Environment

- **Package**: `@azure/mcp@1.0.0` (published October 30, 2025)
- **Platform**: Azure Web App for Linux (Node.js 20 LTS)
- **Managed Identity**: User-Assigned Managed Identity configured and assigned to Web App
- **Permissions**: Database Admin role on Azure Data Explorer cluster (verified working with other apps)
- **Runtime**: Node.js spawning MCP server via `npx -y @azure/mcp@1 server start --namespace kusto --read-only`

## Expected Behavior

According to PR #56 documentation and code (lines 18-24 of `CustomChainedCredential.cs`):

```csharp
/// The credential chain behavior can be controlled via the AZURE_TOKEN_CREDENTIALS environment variable:
/// - "dev": Visual Studio → Visual Studio Code → Azure CLI → Azure PowerShell → Azure Developer CLI
/// - "prod": Environment → Workload Identity → Managed Identity
/// - Specific credential name (e.g., "AzureCliCredential"): Only that credential
```

When `AZURE_TOKEN_CREDENTIALS="prod"` is set, the credential chain should be:
1. EnvironmentCredential
2. WorkloadIdentityCredential
3. **ManagedIdentityCredential** ✅ (Should be included)

When `AZURE_TOKEN_CREDENTIALS="ManagedIdentityCredential"` is set, only ManagedIdentityCredential should be attempted.

## Actual Behavior

The credential chain **always ignores** the `AZURE_TOKEN_CREDENTIALS` environment variable and falls through to `InteractiveBrowserCredential`:

```
Error: The ChainedTokenCredential failed due to an unhandled exception: 
InteractiveBrowserCredential authentication failed: Persistence check failed.
```

The error message suggests that `ManagedIdentityCredential` and `WorkloadIdentityCredential` were never attempted, as the chain fell all the way to the interactive browser credential (which cannot work in server environments without a GUI).

# Findings: Works Locally, Fails in Azure

- **Local environment** (with `az login`): ✅ **WORKS** - Uses AzureCliCredential from "dev" chain
- **Azure Web App** (with Managed Identity + `AZURE_TOKEN_CREDENTIALS="prod"`): ❌ **FAILS** - "prod" chain not activated, falls to InteractiveBrowserCredential

This proves:
1. The MCP server and code implementation work correctly
2. The "dev" credential chain (including AzureCliCredential) functions properly
3. The "prod" credential chain (Environment → WorkloadIdentity → ManagedIdentity) is **not being activated** despite `AZURE_TOKEN_CREDENTIALS="prod"` being set
4. The environment variable is either not being read or not being respected by the .NET runtime in Azure Web App

### 1. Setup Azure Resources

```bash
# Create User-Assigned Managed Identity
az identity create --name myapp-mi --resource-group my-rg

# Create Azure Web App with Node.js 20
az webapp create --name myapp --resource-group my-rg --plan myplan --runtime "NODE:20-lts"

# Assign Managed Identity to Web App
az webapp identity assign --name myapp --resource-group my-rg \
  --identities /subscriptions/{sub-id}/resourcegroups/my-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myapp-mi

# Grant permissions to Azure Data Explorer (or any Azure resource)
# Example: Database Admin role on Kusto cluster
```

### 2. Configure Environment Variables

```bash
az webapp config appsettings set --name myapp --resource-group my-rg --settings \
  AZURE_CLIENT_ID="<managed-identity-client-id>" \
  AZURE_TOKEN_CREDENTIALS="prod"
```

### 3. Node.js Code to Spawn MCP Server

```typescript
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';

// Configure transport with environment variables
const transportConfig = {
  command: 'npx',
  args: ['-y', '@azure/mcp@1', 'server', 'start', '--namespace', 'kusto', '--read-only'],
  env: process.env as Record<string, string>, // Passes all env vars including AZURE_TOKEN_CREDENTIALS
};

// Create MCP client
const transport = new StdioClientTransport(transportConfig);
const client = new Client({ name: 'test', version: '1.0.0' }, { capabilities: { tools: {} } });

// Connect and call tool
await client.connect(transport);
const result = await client.callTool({
  name: 'kusto',
  arguments: { 
    intent: 'query Azure Data Explorer database',
    command: 'kusto_query',
    parameters: { 
      'cluster-uri': 'https://mycluster.kusto.windows.net',
      'database': 'mydb',
      'query': 'MyTable | take 5'
    }
  }
});
```

### 4. Observe Error

```
401 Authentication failed
Error: The ChainedTokenCredential failed due to an unhandled exception: 
InteractiveBrowserCredential authentication failed: Persistence check failed.
```

## Environment Variables Tested (All Failed)

We tried multiple combinations to enable ManagedIdentityCredential:

| Environment Variable | Value | Expected Result | Actual Result |
|---------------------|-------|-----------------|---------------|
| `AZURE_TOKEN_CREDENTIALS` | `"prod"` | Should enable MI | ❌ Ignored, falls to InteractiveBrowser |
| `AZURE_TOKEN_CREDENTIALS` | `"ManagedIdentityCredential"` | Should use MI only | ❌ Ignored, falls to InteractiveBrowser |
| `AZURE_CLIENT_ID` | `<mi-client-id>` | Should target specific MI | ✅ Set correctly but MI never attempted |
| `AZURE_IDENTITY_DISABLE_INTERACTIVE_BROWSER_CREDENTIAL` | `"true"` | Should disable interactive | ❌ Ignored, still attempts interactive |
| `AZURE_IDENTITY_DISABLE_CP1` | `"true"` | Should disable CP1 | ❌ No effect |
| `AZURE_MCP_INCLUDE_PRODUCTION_CREDENTIALS` | `"true"` | Deprecated (old variable) | ❌ Deprecated in PR #56 |

**Note**: `MSI_ENDPOINT` and `MSI_SECRET` are automatically set by Azure Web App runtime and are present in the environment.

## Code Analysis

Looking at the PR #56 code changes in `CustomChainedCredential.cs` (lines 145-159):

```csharp
case "prod":
    // Prod chain: Environment -> WorkloadIdentity -> ManagedIdentity
    AddEnvironmentCredential(credentials);
    AddWorkloadIdentityCredential(credentials, tenantId);
    AddManagedIdentityCredential(credentials);  // ✅ This SHOULD be included
    break;

case "managedidentitycredential":
    AddManagedIdentityCredential(credentials);  // ✅ Direct targeting should work
    break;
```

The code clearly shows that:
1. ✅ `AZURE_TOKEN_CREDENTIALS="prod"` should include `ManagedIdentityCredential` (line 158)
2. ✅ `AZURE_TOKEN_CREDENTIALS="ManagedIdentityCredential"` should target it directly (line 169-171)
3. ✅ Default chain (no env var) **correctly excludes** MI (line 210)

**The implementation appears correct in the C# code, but the runtime behavior does not match.**

## Verification

We confirmed the package version **SHOULD** include PR #56:
- PR #56 merged: September 19, 2025
- PR #56 integrated in release: 0.8.0 (September 18, 2025) per CHANGELOG
- `@azure/mcp@1.0.0` wrapper published: October 30, 2025 ✅
- `@azure/mcp-linux-x64@1.0.0` binary published: October 28, 2025 ✅
- **Timeline confirms the binary SHOULD contain PR #56 code**

However, the runtime behavior suggests either:
1. The npm package binary was compiled from old source code (before PR #56)
2. There's a bug in environment variable reading in the .NET runtime
3. The binary is cached and not reflecting the latest code

## Possible Root Causes

1. **Environment variable not being read**: The C# code may not be reading `AZURE_TOKEN_CREDENTIALS` from environment at runtime
2. **Case sensitivity issue**: Environment variable names might be case-sensitive in .NET runtime but not documented
3. **Node.js wrapper issue**: The npm package may not be passing environment variables correctly to the .NET binary
4. **Cached binary**: The .NET binary included in npm package might be from before PR #56 despite package version being newer
5. **Platform-specific issue**: Linux runtime behavior differs from Windows/development environment

## Impact

This bug is a **critical blocker** for production deployments because:

1. ❌ **Cannot use Managed Identity** - the recommended security best practice for Azure
2. ❌ **Cannot deploy to Azure Web Apps, Function Apps, Container Apps** - all rely on Managed Identity
3. ❌ **Forces use of service principals with secrets** - less secure alternative
4. ❌ **InteractiveBrowserCredential fails in server environments** - no GUI/browser available
5. ❌ **Breaks enterprise security policies** - many organizations mandate Managed Identity

## Workaround Attempted

None found. All approaches to enable ManagedIdentityCredential have failed. The only alternative is to use EnvironmentCredential with service principal (client ID + secret), which is less secure and against Azure best practices.

## Request

Please investigate why `AZURE_TOKEN_CREDENTIALS` is not being respected at runtime and fix the credential chain to properly enable `ManagedIdentityCredential` when:
- `AZURE_TOKEN_CREDENTIALS="prod"` is set
- `AZURE_TOKEN_CREDENTIALS="ManagedIdentityCredential"` is set

Or, if there's a different way to enable Managed Identity in the current implementation, please document it clearly.

## Additional Context

- Related PR: #56 "Improve Authentication Integration and Experience in MCP Server"
- Related commit: 2801db7 "exclude workload and MI creds by default"
- Platform: Azure Web App for Linux with Node.js 20 LTS
- Hosting: Azure Web Apps (but affects Function Apps, Container Apps, AKS, etc.)
- Use case: Querying Azure Data Explorer with Managed Identity authentication

## Logs

Example error from Azure Web App logs:

```
🚀 Starting Azure MCP Server...
Platform: linux
Node version: v20.19.3
AZURE_CLIENT_ID: f659f97e-f4bf-44b0-b705-da9c916a96ff
AZURE_TOKEN_CREDENTIALS: ManagedIdentityCredential
MSI_ENDPOINT: http://169.254.129.6:8081/msi/token
MSI_SECRET: [present]

❌ MCP tool call failed: kusto
{
  "status": 401,
  "message": "Authentication failed. Please run 'az login' to sign in to Azure. Details: The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: Persistence check failed. Inspect inner exception for details. To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azmcp/troubleshooting.",
  "results": {
    "message": "The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: Persistence check failed. Inspect inner exception for details",
    "stackTrace": null,
    "type": "AuthenticationFailedException"
  },
  "duration": 0
}
```

---

**Thank you for your attention to this issue!** This is blocking our production deployment and affects any scenario where Azure MCP Server needs to run in Azure hosting environments with Managed Identity.

**Comment by joshfree** [comment]
@g2vinay @xiangyan99 PTAL

**Comment by matrahul** [comment]
This can resolved via hybrid approach, MI won't work but service principal with Az cli auth will work. i have this set up via hybrid approach.

**Comment by g2vinay** [comment]
Hi @tingwei3931 

Thank you for reporting this issue. 
Looking at the flow, it seems you're using user assigned MI and that isn't getting picked up by the MI credential. 
The root cause is that MI needs the client ID of your user assigned MI. 
I will open a PR to add support for reading the Client ID from the env var. AZURE_CLIENT_ID, which currently isn't being read.

To unblock, you can switch to system assigned MI in your web app.

**Comment by g2vinay** [comment]
@tingwei3931 
This issue is resolved via #1033 
it will ship soon this week on Thursday likely..

**Comment by tingwei3931** [comment]
Hi,

Thanks for the quick response! However, I want to clarify the root cause based on my testing.

The issue is that `AZURE_TOKEN_CREDENTIALS="prod"` is NOT activating the prod chain at all.

EVIDENCE:
In my Azure Web App SSH session, I tested directly:
- ✅ AZURE_TOKEN_CREDENTIALS="prod" is SET (verified with echo)
- ✅ AZURE_CLIENT_ID is SET
- ❌ Error message: "InteractiveBrowserCredential authentication failed"

If the "prod" chain (Environment → WorkloadIdentity → ManagedIdentity) was being used, the error would be about ManagedIdentityCredential failing, NOT InteractiveBrowserCredential.

The fact that InteractiveBrowserCredential is being attempted proves the DEFAULT chain is being used, which means AZURE_TOKEN_CREDENTIALS is being ignored.

I tested BOTH:
- @azure/mcp@1.0.0: Same error
- @azure/mcp@2.0.0-beta.1: Same error

This suggests the published binaries were not compiled with PR #56 changes, or Environment.GetEnvironmentVariable("AZURE_TOKEN_CREDENTIALS") is not working in the Linux runtime.

Can you verify:
1. Were the 1.0.0 and 2.0.0-beta.1 binaries actually compiled with PR #56 code?
2. Is there logging we can enable to see which credential chain is being used?

The AZURE_CLIENT_ID fix is needed too, but the primary issue is that the prod chain isn't being activated at all.

SSH test results attached: 
🧪 Testing MCP Server with AZURE_TOKEN_CREDENTIALS="prod"

=== Environment Variables ===
AZURE_TOKEN_CREDENTIALS: prod
AZURE_CLIENT_ID: f659f97e-f4bf-44b0-b705-da9c916a96ff
MSI_ENDPOINT: http://169.254.129.3:8081/msi/token

📡 Connecting to MCP server (@azure/mcp@1)...
npm info using npm@10.9.2
npm info using node@v20.19.3
✅ Connected!

🔧 Calling kusto tool...
✅ SUCCESS! Authentication worked!
Result: {
  "content": [
    {
      "type": "text",
      "text": "{\"status\":401,\"message\":\"Authentication failed. Please run \\u0027az login\\u0027 to sign in to Azure. Details: The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: Persistence check failed. Inspect inner exception for details. To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azmcp/troubleshooting.\",\"results\":{\"message\":\"The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: Persistence check failed. Inspect inner exception for details\",\"stackTrace\":null,\"type\":\"AuthenticationFailedException\"},\"duration\":0}"
    }
  ],
  "isError": true
}

🧪 Testing MCP Server with @azure/mcp@latest (2.0.0-beta.1)
=== Environment Variables ===
AZURE_TOKEN_CREDENTIALS: prod
AZURE_CLIENT_ID: f659f97e-f4bf-44b0-b705-da9c916a96ff

📡 Connecting to MCP server (@azure/mcp@latest)...
npm info using npm@10.9.2
npm info using node@v20.19.3
npm http fetch GET 200 https://registry.npmjs.org/@azure%2fmcp 147ms (cache revalidated)
✅ Connected!

🔧 Calling kusto tool...
✅ SUCCESS!
Result: {
  "content": [
    {
      "type": "text",
      "text": "{\"status\":401,\"message\":\"Authentication failed. Please run \\u0027az login\\u0027 to sign in to Azure. Details: The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: Persistence check failed. Inspect inner exception for details. To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azmcp/troubleshooting.\",\"results\":{\"message\":\"The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: Persistence check failed. Inspect inner exception for details\",\"stackTrace\":null,\"type\":\"AuthenticationFailedException\"},\"duration\":0}"
    }
  ],
  "isError": true
}


Thanks!

**Comment by tingwei3931** [comment]
Verified the environment variables are correctly set, but authentication still fails due to performing InteractiveBrowserCredential instead of ManagedIdentityCredential:
root@3fd47e5482b4:/home# env | grep AZURE | sort
APPSETTING_AZURE_TOKEN_CREDENTIALS=prod
AZURE_CLIENT_ID=f659f97e-f4bf-44b0-b705-da9c916a96ff
AZURE_TOKEN_CREDENTIALS=prod

**Comment by g2vinay** [comment]
Hi @tingwei3931 

To clarify, currently Interactive Browser credential is currently the standard default fallback, at the end of the credential chain. 
We've updated it to not try Interactive browser credential when you have AZURE_TOKEN_CREDENTIALS set. This change will ship in next release this week.

**Comment by tingwei3931** [comment]
Sounds good. Thanks!

**Comment by g2vinay** [comment]
@tingwei3931 the update was released last week in 2.0.0-beta.2 release. 
Can you try that out  ?

**Comment by tingwei3931** [comment]
Hi, Issue is fixed. Thanks!
