### ISSUE TITLE
VS Code VSIX: Large number of file watchers

### ISSUE THREAD

**Issue by alzimmermsft** [microsoft/mcp#277]
Extension created crazy number of file watchers - is that a bug?

```bash
sudo bash -c '
printf "%-8s %-6s %s\n" WATCHES PID CMD
for p in /proc/[0-9]*; do
  pid=${p#/proc/}
  sum=0
  for fi in "$p"/fdinfo/*; do
    [ -f "$fi" ] || continue
    c=$(grep -c "^inotify" "$fi" 2>/dev/null || true)
    sum=$((sum + c))
  done
  if [ "$sum" -gt 0 ]; then
    cmd=$(tr -d "\0" < "$p/cmdline" | head -c 120)
    printf "%-8s %-6s %s\n" "$sum" "$pid" "$cmd"
  fi
done 2>/dev/null | sort -nr | head
'
```

>WATCHES  PID    CMD
>517372   2384325 /home/xxx/.vscode-server/extensions/ms-azuretools.vscode-azure-mcp-server-0.5.3-linux-x64/server/azmcpserverstart

**Comment by alzimmermsft** [comment]
Copied from https://github.com/Azure/azure-mcp/issues/897

**Comment by joshfree** [comment]
@anuchandy would this be addressed by the namespace performance improvement you're shipping in 0.8.5?

**Comment by karpikpl** [comment]
It's still happening for me in WSL

<img width="1220" height="377" alt="Image" src="https://github.com/user-attachments/assets/80f23dd3-e904-4014-b092-f1e700f7c649" />
